// flow-typed signature: 611934e51a078d6f7fa676a363c256cc
// flow-typed version: <<STUB>>/koa-unless_v^1.0.7/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-unless'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-unless' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-unless/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-unless/index' {
  declare module.exports: $Exports<'koa-unless'>;
}
declare module 'koa-unless/index.js' {
  declare module.exports: $Exports<'koa-unless'>;
}
declare module 'koa-unless/test/test.js' {
  declare module.exports: $Exports<'koa-unless/test/test'>;
}
